---
- name: Change ACL for Normal
  hosts: arista

- name: Change ACL for DR
  arista.eos.eos_acls:
    config:
    - afi: ipv4
      acls:
      - name: test1
        aces:
        - sequence: 35
          log: true
          ttl:
            eq: 33
    state: deleted
